apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      project: roboshop
  template:
    metadata:
      labels:
        app: frontend
        project: roboshop
    spec:
      containers:
      - name: nginx
        image: kesavakadiyala/frontend:VERSION
        resources:
          limits:
            memory: 500Mi
            cpu: 250m
          requests:
            memory: 500Mi
            cpu: 250m
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
